### ISSUE TITLE
ref_id

### ISSUE THREAD

**Issue by khansaadbinhasan** [RoadToML/StockSentiment#1]
give value to ref_id and remove all other statements regarding ref_id

**Comment by RoadToML** [comment]
ref_id was set as primary key for some reason, we can change the Primary key to id_str and get rid of ref_id. 

will be done

**Comment by khansaadbinhasan** [comment]
I do not understand the whole point of ref_id i do not understand what this is supposed to do, I do not think it was in the dataset either, It was set primary key because a table has to have one primary key

**Comment by khansaadbinhasan** [comment]
Sure we need to get rid of `ref_id` but then we need another primary key, We cannot make id_str a primary key because its not unique, it seems like the data has multiple copies of the same json objects

**Comment by RoadToML** [comment]
We dont need primary key for 1 table so ill go ahead and remove ref_id!
